services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    environment:
      - PORT=3000
      - EIEI=${EIEI}
      - NEXT_PUBLIC_EIEI=${NEXT_PUBLIC_EIEI}
